on:
  pull_request:
    branches:
      - deploy/prod
    types:
      - closed # This ensures the workflow is triggered when a PR is merged

name: 🚀 Deploy website to PROD on merge

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          cd ./schoolthrifties-p2p  # Navigate to the correct directory
          npm install
          npm run build:prod

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          local-dir: ./public_html/classifieds.schoolthrifties.co.za/
